DROP TABLE IF EXISTS Books_To_Authors;
DROP TABLE IF EXISTS Authors;
DROP TABLE IF EXISTS Books;

CREATE TABLE IF NOT EXISTS Authors (
  id        BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name  VARCHAR(50) NOT NULL,
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_date TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB, AUTO_INCREMENT = 1, DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS Books (
  id    BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  isbn  VARCHAR(20) UNIQUE NOT NULL,
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_date TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB, AUTO_INCREMENT = 1, DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS Books_To_Authors (
  book_id   BIGINT,
  author_id BIGINT,
  PRIMARY KEY (book_id, author_id),
  CONSTRAINT CONSTR__BOOKS_TO_AUTHORS__BOOK_FK
  FOREIGN KEY BOOKS_FK (book_id) REFERENCES Books (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT CONSTR__BOOKS_TO_AUTHORS__AUTHOR_FK
  FOREIGN KEY AUTHOR_FK (author_id) REFERENCES Authors (id)
    ON DELETE CASCADE ON UPDATE CASCADE
)